fix stdio bug where auto tag is not applied if [ is ANYWHERE in the line, not just at the start

diff --git a/vclod_stdio2log b/vclod_stdio2log
--- a/vclod_stdio2log
+++ b/vclod_stdio2log
@@ -37,7 +37,7 @@ ulimit -s unlimited  # log files might get large, need to let them float in howe
 # If you want to send warnings through stderr, override [ERROR] with [WARNING].
 while IFS='' read -r line; do
   if [[ "$line" =~ [^[:space:]] ]]; then # ignore blank lines
-    new_line="$$ $([[ $line =~ \[.* ]] || echo -n '[LOG] ')$line"
+    new_line="$$ $([[ $line =~ ^\[.* ]] || echo -n '[LOG] ')$line"
     logger "$new_line"
     new_line="$(date +'%F %T') $new_line"
     echo "$new_line" >>$LF
@@ -46,7 +46,7 @@ while IFS='' read -r line; do
 done < "$LOG_FIFO" &
 while IFS='' read -r line; do
   if [[ "$line" =~ [^[:space:]] ]]; then # ignore blank lines
-    new_line="$$ $([[ $line =~ \[.* ]] || echo -n '[ERROR] ')$line"
+    new_line="$$ $([[ $line =~ ^\[.* ]] || echo -n '[ERROR] ')$line"
     logger "$new_line"
     new_line="$(date +'%F %T') $new_line"
     [ $FIRST_ERROR == 1 ] && echo "$$ $LOG_FILE" >>$MAIL_ELF
