use a fifo manager instead of xargs; load functions once+add vcurl; add .para (#3)
details:

switched from using xargs to a custom fifo manager, enabling function propagation.
broke up vclod_helpers into includes/* system
added vcurl functions
extended the test_webserver to cover more test cases
added .para to mimic the do_dir fifo manager
moved ksh check from vclod_run_script to .sh where it should be
got rid of the fifos in vclod_get_semaphore
merged vclod_get_semaphore and vclod_stdio2log into vclod_run_script
run_tests.sh cleanup and bugfixes
made generate_docs handle multiple usages of Variables and added other enhancements
added vclod_mktemp function and used it everywhere
updated sort usage for files to include -n for better prepended number handling
extended .sh doco to include all the includes/* functions... probably need to add info about the collections
.etl fix a bug with grouping by #generate_unique numbers
add a kill trap for both fifo managers (do_dir and .para)
switch from !-z to -n everywhere
favor printf over echo in most places.
attempt at .while buffer fix

diff --git a/vclod_do_dir b/vclod_do_dir
--- a/vclod_do_dir
+++ b/vclod_do_dir
@@ -1,32 +1,35 @@
 #! /bin/ksh
-# Launches all VCLOD batches defined in a directory, running up to VCLOD_JOBS at a time. One of the primary ways of
-# launching VCLOD batches.
+# Launches all VCLOD batches defined in a directory, running up to VCLOD_JOBS at a time. 
 #
-# Usage:
+# Usage (better to just use vclod installed script):
 # ./vclod_do_dir /path/to/dir
-#
 
 [ -z "$VCLOD_BASE_DIR" ] && . "$(dirname "$(readlink -f "$(which "$0")")")/vclod_loadenv"
 
+ulimit -s unlimited  # log files might get large, need to let them float in however much memory is needed/available.
+
 # Argument validation
-: "${VCLOD_BASE_DIR:?}" "${1:?Missing a directory or file to process}"
-: "${VCLOD_JOBS:=10}" # How many sripts to run in parallel
+: "${1:?Missing a directory or file to process}"
+: "${VCLOD_JOBS:=10}" # How many scripts to run in parallel. Must be at least 1 or nothing will happen.
 : "${OPERATIONS_EMAIL:?}" # Email address list to send error output to
-[ -d "$VCLOD_BASE_DIR" ] || { echo VCLOD_BASE_DIR must be an existing directory; exit; }
-[ -d "$LOG_BASE_DIR" ] || { echo LOG_BASE_DIR must be an existing directory; exit; }
-# NOTE: Below comment is for LOG_BASE_DIR auto_docs; MAIL_ELF is used to send batched errors
-MAIL_ELF="${LOG_BASE_DIR:?}/$$.err" # Where to store log files (will also store error output)
+MAIL_ELF="${LOG_BASE_DIR}/$$.err" # used to send batched error emails.
 export MAIL_ELF
 [ -s "$MAIL_ELF" ] && : >"$MAIL_ELF" # force it to start empty
 
 if [ -e "$1" ]; then
-  find "$@" ! -empty -xtype f -regextype posix-egrep -regex "$VCLOD_FILE_REGEX" | sort | xargs -n1 -r -P"$VCLOD_JOBS" "${VCLOD_BASE_DIR%/}/vclod_run_script"
+  PIPE_FIFO="${VCLOD_LOCK_DIR%/}/pipe.$$.fifo" ; mkfifo "$PIPE_FIFO" ; exec 3<>"$PIPE_FIFO" ; add_file_cleanup "$PIPE_FIFO"
+  stdbuf -i0 -o0 -e0 seq 1 "$VCLOD_JOBS" >&3
+  post_exit_trap 'for j in "$(jobs -p)";do kill -SIGINT "$j" 2>/dev/null;done;[ -n "$(jobs -p)" ] && wait'
+  find "$@" ! -empty -xtype f -regextype posix-egrep -regex "$VCLOD_FILE_REGEX" | sort -n | while read f ; do
+    stdbuf -i0 -o0 -e0 read dummy <&3
+    ( export MYPID="$(exec sh -c 'echo $PPID')"; . "${VCLOD_BASE_DIR%/}/vclod_run_script" "$f"; ret="$?"; stdbuf -i0 -o0 -e0 printf 'a\n' >&3; exit "$ret" ) &
+  done  # WAS: xargs -n1 -r -P"$VCLOD_JOBS" "${VCLOD_BASE_DIR%/}/vclod_run_script"
+  [ -n "$(jobs -p)" ] && wait
 else
-  . "${VCLOD_BASE_DIR%/}/vclod_helpers" || exit $?
-  export pIN_FILE="$(mktemp)" # the p stands for private and prevents it from showing up in the doco
-  add_file_cleanup "$pIN_FILE"
+  export MYPID="$$"
+  export pIN_FILE="$(vclod_mktemp)" # the p stands for private and prevents it from showing up in the doco
   cat >"$pIN_FILE" # not sure why this works here but not in run_script
-  . "${VCLOD_BASE_DIR%/}/vclod_run_script" <"$pIN_FILE" 
+  . "${VCLOD_BASE_DIR%/}/vclod_run_script" <"$pIN_FILE"
 fi
 ret=$?
 [ -s "$MAIL_ELF" ] && [ "$IS_TERMINAL" -eq 0 ] && mail -s "Script error digest on $(hostname)" "$OPERATIONS_EMAIL" <"$MAIL_ELF"
